// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfbQpP3rTig5XxmdbR37_Eqrq2iTl5u4',
    appId: '1:392760923093:android:e4dbc514b69523e741635c',
    messagingSenderId: '392760923093',
    projectId: 'finwise-ea77d',
    storageBucket: 'finwise-ea77d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC39J9ptvIWdyKLoXgfE0Gvd7u_eZTp-TU',
    appId: '1:392760923093:ios:cbe656b34bca60c141635c',
    messagingSenderId: '392760923093',
    projectId: 'finwise-ea77d',
    storageBucket: 'finwise-ea77d.firebasestorage.app',
    iosClientId: '392760923093-36bij9qrr4m6ojbstf7khmh1jqfb4ikp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TgK8LskMM_uH2XoN5BpsVFSUraIPW2A',
    appId: '1:392760923093:web:7b014fd08327dd9641635c',
    messagingSenderId: '392760923093',
    projectId: 'finwise-ea77d',
    authDomain: 'finwise-ea77d.firebaseapp.com',
    storageBucket: 'finwise-ea77d.firebasestorage.app',
    measurementId: 'G-YTEMSCR96H',
  );

}